Reethu RG Thota - 1RVU22CSE128

### Sigmoid

In [3]:
import math 
def basic_sigmoid(x):
    """
    Compute sigmoid of x.
    
    Arguments:
    x == A scalar
    
    Return:
    s -- sigmoid(x)
    """
    
    s = 1/(1+ math.exp(-x))
    
    return s

In [4]:
basic_sigmoid(-1)

0.2689414213699951

In [5]:
import numpy as np

x = np.array([1, 2, 3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [6]:
# GRADED FUNCTION: sigmoid

import numpy as np

def numpy_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    result = 1/(1+ np.exp(-x))
    return result

In [7]:
numpy_sigmoid(-1)

0.2689414213699951

In [8]:
x = np.array([1, 2, 3])
numpy_sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

### Sigmoid Gradient

In [9]:
import numpy as np 
def sigmoid_derivative(x):
    s = (1 - numpy_sigmoid(x))*(numpy_sigmoid(x))
    return s

In [10]:
x = np.array([1, 2, 3])
print("sigmoid_derivative(x) =", str(sigmoid_derivative(x)))

sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]


### Image to vector

In [11]:
# GRADED FUNCTION: image2vector
# flattens a 3D array into a 2D array or vector with (image.shape[0] * image.shape[1] * image.shape[2], 1) as the dimension.
def image2vector(image):
    vec = image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))
    return vec


In [12]:
# This is a 3 x 3 x 2 array
image = np.array([[[ 0.67826139, 0.29380381],
[0.90714982, 0.52835647],
[0.4215251, 0.45017551]],
                  
[[0.92814219, 0.96677647],
[0.85304703, 0.52351845],
[0.19981397, 0.27417313]],

[[0.68659855, 0.00533165],
[0.10828313, 0.49978937],
[0.34144279, 0.94636077]]])

print("image2vector(image) =", str(image2vector(image)))


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.68659855]
 [0.00533165]
 [0.10828313]
 [0.49978937]
 [0.34144279]
 [0.94636077]]


### Normalise Rows

In [13]:
# GRADED FUNCTION: normalise rows

def normaliseRows(x):
    """
    Implement a function that normalises each row of the matrix x (to have unit length)
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalised (by row) numpy matrix.
    """
    
    x_norm = np.linalg.norm(x, axis=1, keepdims = True) # finds euclidean distance or normal between all elements in the row
    x = x / x_norm
    return x

In [14]:
x = np.array([
    [0, 1000, 4],
    [2, 4, 6]])

print("normaliseRows(x) =", normaliseRows(x))

[[1000.00799997]
 [   7.48331477]]
normaliseRows(x) = [[0.         0.999992   0.00399997]
 [0.26726124 0.53452248 0.80178373]]


### Broadcasting and the softmax function

In [15]:
# GRADED FUNCTION: softmax

def softmax(x):
    """
    Calculates softmax for each row of the input x

    Argument:
        x -- A numpy matrix of shape (n, m)
        
    Returns:
    x -- A numpy matrix with softmax of shape (n, m)
    """
    
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims = True)
    x = x_exp/x_sum
    
    return x

In [16]:
x = np.array([
    [9, 2, 5, 0, 0],
    [3, 4, 5, 6, 7]])

print("softmax(x) =", softmax(x))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [1.16562310e-02 3.16849208e-02 8.61285444e-02 2.34121657e-01
  6.36408647e-01]]


### Vectorisation

In [17]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### Classic dot product of vectors implementation
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i] * x2[i]
toc = time.process_time()
print("dot = " + str(dot) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic outer product implementation 
tic = time.process_time()
outer = np.zeros((len(x1), len(x2)))
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i, j] = x1[i] * x2[j]
toc = time.process_time()
print("outer = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic elementwise implementation
tic = time.process_time() 
mul = np.zeros(len(x1))
for i in range(len(x1)): 
    mul[i] =  x1[1] * x2[i]
toc = time.process_time()
print("elementwise multiplication = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Classic general dot product implementation
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time() 
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print("gdot = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms") 


dot = 278
 --- Computation time = 0.236000000000125ms


outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

In [18]:
### Vectorised dot product
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print("dot = " + str(dot) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised outer product
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print("outer = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised elementwise multiplication
tic = time.process_time() 
mul = np.multiply(x1,x2)
toc = time.process_time()
print("elementwise multiplication = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms\n\n") 

### Vectorised general dot product
tic = time.process_time() 
dot = np.dot(W,x1)
toc = time.process_time()
print("gdot = " + str(outer) + "\n --- Computation time = " + str(1000*(toc - tic)) + "ms") 

dot = 278
 --- Computation time = 0.052999999999858716ms


outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 --- Computation time = 0.31999999999987594ms


elementwise multiplication = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 2

### L1 & L2 Loss Function

In [19]:
# GRADED FUNCTION: L1
def L1(yHat, y):
    loss = np.sum(np.absolute(y - yHat))
    return loss

In [20]:
yHat = np.array([1, 6, 1, 1, 1])
y = np.array([1, 1, 1, 5, 1])
print("L1 = " + str(L1(yHat, y)))

L1 = 9


In [21]:
# GRADED FUNCTION: L2
def L2(yHat, y):
    loss = np.sum((np.absolute(y - yHat))**2)
    return loss

In [22]:
yHat = np.array([1, 6, 1, 1, 1])
y = np.array([1, 1, 1, 5, 1])
print("L2 = " + str(L2(yHat, y)))

L2 = 41
